__default__:
    mem: 24g
    partition: quick,norm
    time: '4:00:00'
    scratch: lscratch:1 

mkfastq:
    mem: 160g
    partition: norm
    time: '100:00:00'

ref_premRNA:
    mem: 160g
    partition: norm
    time: '100:00:00'

cellranger_count:
    mem: 220g
    partition: norm
    time: '240:00:00'

link:
    mem: 24g
    partition: quick,norm
    time: '2:00:00'

diem:
    mem: 128g
    partition: quick,norm
    time: '2:00:00'

reanalysis:
    mem: 220g
    partition: norm
    time: '240:00:00'

link_reanalysis:
    mem: 24g
    partition: quick,norm
    time: '2:00:00'

seurat:
    mem: 200g
    partition: quick,norm
    time: '4:00:00'
    scratch: lscratch:100

singleR:
    mem: 200g
    partition: quick,norm
    time: '4:00:00'
    scratch: lscratch:100

combine:
    mem: 200g
    partition: quick,norm
    time: '4:00:00'
    scratch: lscratch:100

cogaps:
    mem: 200g
    partition: norm
    time: '10:00:00'
    scratch: lscratch:100

BAFExtract:
    mem: 200g
    partition: quick,norm
    time: '4:00:00'

conicsmat:
    mem: 200g
    partition: norm
    time: '10:00:00'
    scratch: lscratch:100
